# Build & deploy documentation

name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches:
      - master
  # Triggers the workflow on pull
  pull_request:
    branches:
      - master
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SRC_DIR: public

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.67.1/hugo_extended_0.67.1_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.67.1_Linux-64bit.deb
          
      - name: Run and build Hugo
        run: |
          hugo --minify
          rm ${{ env.SRC_DIR }}/product-sitemap.xml

      - name: Deploy documentation
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ env.SRC_DIR }}/*
          host: ${{ secrets.PROD_HOST }}
          remote: /var/www/docs.conholdate.app
          user: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
